# The URL the site will be built for
base_url = "https://hello.chroni.cc"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

author = "Kurt Thomas Steinert"
title = "chronicc"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
copyright.year = "2025"

navigation = [
    { url = "$BASE_URL", title = "Home" },
    { url = "$BASE_URL/cv", title = "CV" },
]

social = [
    { icon = "github", url = "https://github.com/chronicc" },
    { icon = "medium", url = "https://blog.chroni.cc" },
    { icon = "linkedin", url = "https://www.linkedin.com/in/contact-steinert/" },
]
